version: '3'
volumes:
    front_node_modules:
    api_node_modules:
services:
    react-frontend:
        image: node:lts-slim
        command: bash -c "npm install && npm run start"
        volumes:
            - ./react-frontend:/front
            - front_node_modules:/front/node_modules
        working_dir: /front
        ports: 
            - "3000:3000"
        links:
            - node-api-server # APIとか依存するものを書く
    node-api-server:
        image: node:lts-slim
        command: bash -c "npm install && node index.js"
        volumes:
            - ./node-api-server:/src
            - api_node_modules:/src/node_modules
        working_dir: /src
        expose:
            - "8080"
        ports: 
            - "8080:8080"
